#COMAKE2 edit-mode: -*- Makefile -*-
####################32Bit Mode####################
ifeq ($(shell uname -m),i686)
CC=gcc
CXX=g++
CXXFLAGS=-g \
  -pipe \
  -W \
  -Wall \
  -fPIC
CFLAGS=-g \
  -pipe \
  -W \
  -Wall \
  -fPIC
CPPFLAGS=-D_GNU_SOURCE \
  -D__STDC_LIMIT_MACROS \
  -DVERSION=\"1.9.8.7\"
INCPATH=-I. \
  -I./include \
  -I./output \
  -I./output/include \
  -I../simple_skiplist/output/include
DEP_INCPATH=

#============ CCP vars ============
CCHECK=@ccheck.py
CCHECK_FLAGS=
PCLINT=@pclint
PCLINT_FLAGS=
CCP=@ccp.py
CCP_FLAGS=


#COMAKE UUID
COMAKE_MD5=60ebda090ef5068462e5fc57dd434969  COMAKE


.PHONY:all
all:comake2_makefile_check test_sconfig libsconfig.a 
	@echo "[[1;32;40mCOMAKE:BUILD[0m][Target:'[1;32;40mall[0m']"
	@echo "make all done"

.PHONY:comake2_makefile_check
comake2_makefile_check:
	@echo "[[1;32;40mCOMAKE:BUILD[0m][Target:'[1;32;40mcomake2_makefile_check[0m']"
	#in case of error, update 'Makefile' by 'comake2'
	@echo "$(COMAKE_MD5)">comake2.md5
	@md5sum -c --status comake2.md5
	@rm -f comake2.md5

.PHONY:ccpclean
ccpclean:
	@echo "[[1;32;40mCOMAKE:BUILD[0m][Target:'[1;32;40mccpclean[0m']"
	@echo "make ccpclean done"

.PHONY:clean
clean:ccpclean
	@echo "[[1;32;40mCOMAKE:BUILD[0m][Target:'[1;32;40mclean[0m']"
	rm -rf test_sconfig
	rm -rf ./output/bin/test_sconfig
	rm -rf libsconfig.a
	rm -rf ./output/lib/libsconfig.a
	rm -rf ./output/include/sconfig.h
	rm -rf test_sconfig_test_sconfig.o
	rm -rf sconfig_sconfig.o

.PHONY:dist
dist:
	@echo "[[1;32;40mCOMAKE:BUILD[0m][Target:'[1;32;40mdist[0m']"
	tar czvf output.tar.gz output
	@echo "make dist done"

.PHONY:distclean
distclean:clean
	@echo "[[1;32;40mCOMAKE:BUILD[0m][Target:'[1;32;40mdistclean[0m']"
	rm -f output.tar.gz
	@echo "make distclean done"

.PHONY:love
love:
	@echo "[[1;32;40mCOMAKE:BUILD[0m][Target:'[1;32;40mlove[0m']"
	@echo "make love done"

test_sconfig:libsconfig.a \
  test_sconfig_test_sconfig.o \
  libsconfig.a \
  ../simple_skiplist/output/lib/libslist.a
	@echo "[[1;32;40mCOMAKE:BUILD[0m][Target:'[1;32;40mtest_sconfig[0m']"
	$(CXX) test_sconfig_test_sconfig.o \
  libsconfig.a -Xlinker "-(" ../simple_skiplist/output/lib/libslist.a  -lpthread \
  -lrt -Xlinker "-)" -o test_sconfig
	mkdir -p ./output/bin
	cp -f --link test_sconfig ./output/bin

libsconfig.a:sconfig_sconfig.o \
  sconfig.h
	@echo "[[1;32;40mCOMAKE:BUILD[0m][Target:'[1;32;40mlibsconfig.a[0m']"
	ar crs libsconfig.a sconfig_sconfig.o
	mkdir -p ./output/lib
	cp -f --link libsconfig.a ./output/lib
	mkdir -p ./output/include
	cp -f --link sconfig.h ./output/include

test_sconfig_test_sconfig.o:test_sconfig.c \
  sconfig.h
	@echo "[[1;32;40mCOMAKE:BUILD[0m][Target:'[1;32;40mtest_sconfig_test_sconfig.o[0m']"
	$(CC) -c $(INCPATH) $(DEP_INCPATH) $(CPPFLAGS) $(CFLAGS)  -o test_sconfig_test_sconfig.o test_sconfig.c

sconfig_sconfig.o:sconfig.c \
  sconfig.h
	@echo "[[1;32;40mCOMAKE:BUILD[0m][Target:'[1;32;40msconfig_sconfig.o[0m']"
	$(CC) -c $(INCPATH) $(DEP_INCPATH) $(CPPFLAGS) $(CFLAGS)  -o sconfig_sconfig.o sconfig.c

endif #ifeq ($(shell uname -m),i686)


