#COMAKE2 edit-mode: -*- Makefile -*-
####################64Bit Mode####################
ifeq ($(shell uname -m),x86_64)
CC=gcc
CXX=g++
CXXFLAGS=-g \
  -pipe \
  -W \
  -Wall \
  -fPIC
CFLAGS=-g \
  -pipe \
  -W \
  -Wall \
  -fPIC
CPPFLAGS=-D_GNU_SOURCE \
  -D__STDC_LIMIT_MACROS \
  -DVERSION=\"1.9.8.7\"
INCPATH=-I. \
  -I./include \
  -I./output \
  -I./output/include
DEP_INCPATH=

#============ CCP vars ============
CCHECK=@ccheck.py
CCHECK_FLAGS=
PCLINT=@pclint
PCLINT_FLAGS=
CCP=@ccp.py
CCP_FLAGS=


#COMAKE UUID
COMAKE_MD5=35c69bfb4c72b6654b0e02084690c0e5  COMAKE


.PHONY:all
all:comake2_makefile_check test_slist libslist.a 
	@echo "[[1;32;40mCOMAKE:BUILD[0m][Target:'[1;32;40mall[0m']"
	@echo "make all done"

.PHONY:comake2_makefile_check
comake2_makefile_check:
	@echo "[[1;32;40mCOMAKE:BUILD[0m][Target:'[1;32;40mcomake2_makefile_check[0m']"
	#in case of error, update 'Makefile' by 'comake2'
	@echo "$(COMAKE_MD5)">comake2.md5
	@md5sum -c --status comake2.md5
	@rm -f comake2.md5

.PHONY:ccpclean
ccpclean:
	@echo "[[1;32;40mCOMAKE:BUILD[0m][Target:'[1;32;40mccpclean[0m']"
	@echo "make ccpclean done"

.PHONY:clean
clean:ccpclean
	@echo "[[1;32;40mCOMAKE:BUILD[0m][Target:'[1;32;40mclean[0m']"
	rm -rf test_slist
	rm -rf ./output/bin/test_slist
	rm -rf libslist.a
	rm -rf ./output/lib/libslist.a
	rm -rf ./output/include/slist.h
	rm -rf test_slist_test_slist.o
	rm -rf slist_slist.o

.PHONY:dist
dist:
	@echo "[[1;32;40mCOMAKE:BUILD[0m][Target:'[1;32;40mdist[0m']"
	tar czvf output.tar.gz output
	@echo "make dist done"

.PHONY:distclean
distclean:clean
	@echo "[[1;32;40mCOMAKE:BUILD[0m][Target:'[1;32;40mdistclean[0m']"
	rm -f output.tar.gz
	@echo "make distclean done"

.PHONY:love
love:
	@echo "[[1;32;40mCOMAKE:BUILD[0m][Target:'[1;32;40mlove[0m']"
	@echo "make love done"

test_slist:libslist.a \
  test_slist_test_slist.o \
  libslist.a
	@echo "[[1;32;40mCOMAKE:BUILD[0m][Target:'[1;32;40mtest_slist[0m']"
	$(CXX) test_slist_test_slist.o \
  libslist.a -Xlinker "-("   -lpthread \
  -lrt -Xlinker "-)" -o test_slist
	mkdir -p ./output/bin
	cp -f --link test_slist ./output/bin

libslist.a:slist_slist.o \
  slist.h
	@echo "[[1;32;40mCOMAKE:BUILD[0m][Target:'[1;32;40mlibslist.a[0m']"
	ar crs libslist.a slist_slist.o
	mkdir -p ./output/lib
	cp -f --link libslist.a ./output/lib
	mkdir -p ./output/include
	cp -f --link slist.h ./output/include

test_slist_test_slist.o:test_slist.c \
  slist.h
	@echo "[[1;32;40mCOMAKE:BUILD[0m][Target:'[1;32;40mtest_slist_test_slist.o[0m']"
	$(CC) -c $(INCPATH) $(DEP_INCPATH) $(CPPFLAGS) $(CFLAGS)  -o test_slist_test_slist.o test_slist.c

slist_slist.o:slist.c \
  slist.h
	@echo "[[1;32;40mCOMAKE:BUILD[0m][Target:'[1;32;40mslist_slist.o[0m']"
	$(CC) -c $(INCPATH) $(DEP_INCPATH) $(CPPFLAGS) $(CFLAGS)  -o slist_slist.o slist.c

endif #ifeq ($(shell uname -m),x86_64)


