#COMAKE2 edit-mode: -*- Makefile -*-
####################64Bit Mode####################
ifeq ($(shell uname -m),x86_64)
CC=gcc
CXX=g++
CXXFLAGS=-g \
  -pipe \
  -W \
  -Wall \
  -fPIC
CFLAGS=-g \
  -pipe \
  -W \
  -Wall \
  -fPIC
CPPFLAGS=-D_GNU_SOURCE \
  -D__STDC_LIMIT_MACROS \
  -DVERSION=\"1.9.8.7\"
INCPATH=-I. \
  -I./include \
  -I./output \
  -I./output/include
DEP_INCPATH=

#============ CCP vars ============
CCHECK=@ccheck.py
CCHECK_FLAGS=
PCLINT=@pclint
PCLINT_FLAGS=
CCP=@ccp.py
CCP_FLAGS=


#COMAKE UUID
COMAKE_MD5=1ea275de5da75da17a8fcdb4ec4eaaeb  COMAKE


.PHONY:all
all:comake2_makefile_check test_slog libslog.a 
	@echo "[[1;32;40mCOMAKE:BUILD[0m][Target:'[1;32;40mall[0m']"
	@echo "make all done"

.PHONY:comake2_makefile_check
comake2_makefile_check:
	@echo "[[1;32;40mCOMAKE:BUILD[0m][Target:'[1;32;40mcomake2_makefile_check[0m']"
	#in case of error, update 'Makefile' by 'comake2'
	@echo "$(COMAKE_MD5)">comake2.md5
	@md5sum -c --status comake2.md5
	@rm -f comake2.md5

.PHONY:ccpclean
ccpclean:
	@echo "[[1;32;40mCOMAKE:BUILD[0m][Target:'[1;32;40mccpclean[0m']"
	@echo "make ccpclean done"

.PHONY:clean
clean:ccpclean
	@echo "[[1;32;40mCOMAKE:BUILD[0m][Target:'[1;32;40mclean[0m']"
	rm -rf test_slog
	rm -rf ./output/bin/test_slog
	rm -rf libslog.a
	rm -rf ./output/lib/libslog.a
	rm -rf ./output/include/slog.h
	rm -rf test_slog_test_slog.o
	rm -rf slog_slog.o

.PHONY:dist
dist:
	@echo "[[1;32;40mCOMAKE:BUILD[0m][Target:'[1;32;40mdist[0m']"
	tar czvf output.tar.gz output
	@echo "make dist done"

.PHONY:distclean
distclean:clean
	@echo "[[1;32;40mCOMAKE:BUILD[0m][Target:'[1;32;40mdistclean[0m']"
	rm -f output.tar.gz
	@echo "make distclean done"

.PHONY:love
love:
	@echo "[[1;32;40mCOMAKE:BUILD[0m][Target:'[1;32;40mlove[0m']"
	@echo "make love done"

test_slog:libslog.a \
  test_slog_test_slog.o \
  libslog.a
	@echo "[[1;32;40mCOMAKE:BUILD[0m][Target:'[1;32;40mtest_slog[0m']"
	$(CXX) test_slog_test_slog.o \
  libslog.a -Xlinker "-("   -lpthread \
  -lrt -Xlinker "-)" -o test_slog
	mkdir -p ./output/bin
	cp -f --link test_slog ./output/bin

libslog.a:slog_slog.o \
  slog.h
	@echo "[[1;32;40mCOMAKE:BUILD[0m][Target:'[1;32;40mlibslog.a[0m']"
	ar crs libslog.a slog_slog.o
	mkdir -p ./output/lib
	cp -f --link libslog.a ./output/lib
	mkdir -p ./output/include
	cp -f --link slog.h ./output/include

test_slog_test_slog.o:test_slog.c \
  slog.h
	@echo "[[1;32;40mCOMAKE:BUILD[0m][Target:'[1;32;40mtest_slog_test_slog.o[0m']"
	$(CC) -c $(INCPATH) $(DEP_INCPATH) $(CPPFLAGS) $(CFLAGS)  -o test_slog_test_slog.o test_slog.c

slog_slog.o:slog.c \
  slog.h
	@echo "[[1;32;40mCOMAKE:BUILD[0m][Target:'[1;32;40mslog_slog.o[0m']"
	$(CC) -c $(INCPATH) $(DEP_INCPATH) $(CPPFLAGS) $(CFLAGS)  -o slog_slog.o slog.c

endif #ifeq ($(shell uname -m),x86_64)


