#COMAKE2 edit-mode: -*- Makefile -*-
####################32Bit Mode####################
ifeq ($(shell uname -m),i686)
CC=gcc
CXX=g++
CXXFLAGS=-g \
  -pipe \
  -W \
  -Wall \
  -fPIC
CFLAGS=-g \
  -pipe \
  -W \
  -Wall \
  -fPIC
CPPFLAGS=-D_GNU_SOURCE \
  -D__STDC_LIMIT_MACROS \
  -DVERSION=\"1.9.8.7\"
INCPATH=-I. \
  -I./include \
  -I./output \
  -I./output/include
DEP_INCPATH=

#============ CCP vars ============
CCHECK=@ccheck.py
CCHECK_FLAGS=
PCLINT=@pclint
PCLINT_FLAGS=
CCP=@ccp.py
CCP_FLAGS=


#COMAKE UUID
COMAKE_MD5=e4b06c1e75052c95730fbfdda9921d0b  COMAKE


.PHONY:all
all:comake2_makefile_check test_shash libshash.a 
	@echo "[[1;32;40mCOMAKE:BUILD[0m][Target:'[1;32;40mall[0m']"
	@echo "make all done"

.PHONY:comake2_makefile_check
comake2_makefile_check:
	@echo "[[1;32;40mCOMAKE:BUILD[0m][Target:'[1;32;40mcomake2_makefile_check[0m']"
	#in case of error, update 'Makefile' by 'comake2'
	@echo "$(COMAKE_MD5)">comake2.md5
	@md5sum -c --status comake2.md5
	@rm -f comake2.md5

.PHONY:ccpclean
ccpclean:
	@echo "[[1;32;40mCOMAKE:BUILD[0m][Target:'[1;32;40mccpclean[0m']"
	@echo "make ccpclean done"

.PHONY:clean
clean:ccpclean
	@echo "[[1;32;40mCOMAKE:BUILD[0m][Target:'[1;32;40mclean[0m']"
	rm -rf test_shash
	rm -rf ./output/bin/test_shash
	rm -rf libshash.a
	rm -rf ./output/lib/libshash.a
	rm -rf ./output/include/shash.h
	rm -rf test_shash_test_shash.o
	rm -rf shash_shash.o

.PHONY:dist
dist:
	@echo "[[1;32;40mCOMAKE:BUILD[0m][Target:'[1;32;40mdist[0m']"
	tar czvf output.tar.gz output
	@echo "make dist done"

.PHONY:distclean
distclean:clean
	@echo "[[1;32;40mCOMAKE:BUILD[0m][Target:'[1;32;40mdistclean[0m']"
	rm -f output.tar.gz
	@echo "make distclean done"

.PHONY:love
love:
	@echo "[[1;32;40mCOMAKE:BUILD[0m][Target:'[1;32;40mlove[0m']"
	@echo "make love done"

test_shash:libshash.a \
  test_shash_test_shash.o \
  libshash.a
	@echo "[[1;32;40mCOMAKE:BUILD[0m][Target:'[1;32;40mtest_shash[0m']"
	$(CXX) test_shash_test_shash.o \
  libshash.a -Xlinker "-("   -lpthread \
  -lrt -Xlinker "-)" -o test_shash
	mkdir -p ./output/bin
	cp -f --link test_shash ./output/bin

libshash.a:shash_shash.o \
  shash.h
	@echo "[[1;32;40mCOMAKE:BUILD[0m][Target:'[1;32;40mlibshash.a[0m']"
	ar crs libshash.a shash_shash.o
	mkdir -p ./output/lib
	cp -f --link libshash.a ./output/lib
	mkdir -p ./output/include
	cp -f --link shash.h ./output/include

test_shash_test_shash.o:test_shash.c \
  shash.h
	@echo "[[1;32;40mCOMAKE:BUILD[0m][Target:'[1;32;40mtest_shash_test_shash.o[0m']"
	$(CC) -c $(INCPATH) $(DEP_INCPATH) $(CPPFLAGS) $(CFLAGS)  -o test_shash_test_shash.o test_shash.c

shash_shash.o:shash.c \
  shash.h
	@echo "[[1;32;40mCOMAKE:BUILD[0m][Target:'[1;32;40mshash_shash.o[0m']"
	$(CC) -c $(INCPATH) $(DEP_INCPATH) $(CPPFLAGS) $(CFLAGS)  -o shash_shash.o shash.c

endif #ifeq ($(shell uname -m),i686)


